"""child_name__null

Revision ID: abed312fadad
Revises: 66ddd02784bb
Create Date: 2025-11-14 11:10:39.047437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abed312fadad'
down_revision: Union[str, Sequence[str], None] = '66ddd02784bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'child_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('children', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('children', 'child_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
